import type { DeviceSpec, ExportSize } from "@/types/device";

export const DEVICES: Record<string, DeviceSpec> = {
  "iphone-6.9": {
    id: "iphone-6.9",
    name: 'iPhone 16 Pro Max (6.9")',
    platform: "ios",
    width: 1320,
    height: 2868,
    screenX: 0,
    screenY: 0,
    screenWidth: 1320,
    screenHeight: 2868,
    cornerRadius: 120,
  },
  "iphone-6.7": {
    id: "iphone-6.7",
    name: 'iPhone 15 Plus (6.7")',
    platform: "ios",
    width: 1290,
    height: 2796,
    screenX: 0,
    screenY: 0,
    screenWidth: 1290,
    screenHeight: 2796,
    cornerRadius: 110,
  },
  "iphone-6.1": {
    id: "iphone-6.1",
    name: 'iPhone 15 (6.1")',
    platform: "ios",
    width: 1179,
    height: 2556,
    screenX: 0,
    screenY: 0,
    screenWidth: 1179,
    screenHeight: 2556,
    cornerRadius: 100,
  },
  "iphone-5.5": {
    id: "iphone-5.5",
    name: 'iPhone 8 Plus (5.5")',
    platform: "ios",
    width: 1242,
    height: 2208,
    screenX: 0,
    screenY: 0,
    screenWidth: 1242,
    screenHeight: 2208,
    cornerRadius: 0,
  },
  "ipad-13": {
    id: "ipad-13",
    name: 'iPad Pro 13"',
    platform: "ios",
    width: 2064,
    height: 2752,
    screenX: 0,
    screenY: 0,
    screenWidth: 2064,
    screenHeight: 2752,
    cornerRadius: 40,
  },
  "ipad-12.9": {
    id: "ipad-12.9",
    name: 'iPad Pro 12.9"',
    platform: "ios",
    width: 2048,
    height: 2732,
    screenX: 0,
    screenY: 0,
    screenWidth: 2048,
    screenHeight: 2732,
    cornerRadius: 40,
  },
  "android-phone": {
    id: "android-phone",
    name: "Android Phone",
    platform: "android",
    width: 1080,
    height: 1920,
    screenX: 0,
    screenY: 0,
    screenWidth: 1080,
    screenHeight: 1920,
    cornerRadius: 60,
  },
  "android-tablet-7": {
    id: "android-tablet-7",
    name: 'Android Tablet 7"',
    platform: "android",
    width: 1200,
    height: 1920,
    screenX: 0,
    screenY: 0,
    screenWidth: 1200,
    screenHeight: 1920,
    cornerRadius: 30,
  },
  "android-tablet-10": {
    id: "android-tablet-10",
    name: 'Android Tablet 10"',
    platform: "android",
    width: 1600,
    height: 2560,
    screenX: 0,
    screenY: 0,
    screenWidth: 1600,
    screenHeight: 2560,
    cornerRadius: 30,
  },
};

export const EXPORT_SIZES: ExportSize[] = [
  {
    label: 'iPhone 6.9" (Required)',
    width: 1320,
    height: 2868,
    platform: "ios",
    device: "iPhone 16 Pro Max",
    required: true,
  },
  {
    label: 'iPhone 6.7"',
    width: 1290,
    height: 2796,
    platform: "ios",
    device: "iPhone 15 Plus",
    required: false,
  },
  {
    label: 'iPhone 6.1"',
    width: 1179,
    height: 2556,
    platform: "ios",
    device: "iPhone 15",
    required: false,
  },
  {
    label: 'iPhone 5.5"',
    width: 1242,
    height: 2208,
    platform: "ios",
    device: "iPhone 8 Plus",
    required: false,
  },
  {
    label: 'iPad 13" (Required)',
    width: 2064,
    height: 2752,
    platform: "ios",
    device: "iPad Pro 13",
    required: true,
  },
  {
    label: 'iPad 12.9"',
    width: 2048,
    height: 2732,
    platform: "ios",
    device: "iPad Pro 12.9",
    required: false,
  },
  {
    label: "Android Phone",
    width: 1080,
    height: 1920,
    platform: "android",
    device: "Phone",
    required: true,
  },
  {
    label: 'Android Tablet 7"',
    width: 1200,
    height: 1920,
    platform: "android",
    device: '7" Tablet',
    required: false,
  },
  {
    label: 'Android Tablet 10"',
    width: 1600,
    height: 2560,
    platform: "android",
    device: '10" Tablet',
    required: false,
  },
];

export const DEFAULT_DEVICE: DeviceSpec = DEVICES["iphone-6.9"];
